# Generated by Django 5.1 on 2024-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_table_order_customer_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
